server:
  port: 8080

spring:
  application:
    name: nginx-request-logging
  task:
    execution:
      pool:
        core-size: 4
        max-size: 16
  elasticsearch:
    uris: ${ES_URIS:http://localhost:9200}
    username: ${ES_USERNAME:elastic}
    password: ${ES_PASSWORD:elastic}
